---
# Common ignition gateway settings
x-ignition-common: &ignition-common
  image: etknorr/common-docker-ignition:8.1.42
  networks:
    - default

services:
  gateway:
    <<: *ignition-common
    container_name: ${GATEWAY_NAME}
    volumes:
      # Bind mount the data-gateway directory to the container's workdir
      - ./data-gateway:/workdir
      # Gwbk file to restore from
      - ./gw-init/gateway.gwbk:/restore.gwbk
      # Modules to be installed
      - ./module-init/Tag-CICD.modl:/modules/Tag-CICD.modl
      # Tags to be imported
      - ./tags:/tags
    labels:
      - traefik.enable=true
      - traefik.hostname=${GATEWAY_NAME}
    environment:
      TZ: America/Los_Angeles
    command: >
      -n ${GATEWAY_NAME}
      -h 80
      -s 443
      -a ${GATEWAY_NAME}.localtest.me
      -r /restore.gwbk
      --
      -Dignition.allowunsignedmodules=true

  tag-import:
    <<: *ignition-common
    depends_on:
      gateway:
        condition: service_healthy
    environment:
      TZ: America/Los_Angeles
    entrypoint: []
    command: >
      tag-import.sh -c d -d /tags -a --force --debug gateway:8088
    volumes:
      - ./scripts/tag-import.sh:/usr/local/bin/tag-import.sh
      - ./tags:/tags

  db:
    image: postgres:16.4
    hostname: db-${GATEWAY_NAME}
    container_name: db-${GATEWAY_NAME}
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "localhost", "-U", "ignition"]
      interval: 10s
      timeout: 20s
      retries: 10
    # Uncomment on local for database management. Connections can be made at datadash-db.localtest.me:5430, or whichever port you set
    # ports:
    #   - "5430:5432"
    networks:
      default:
        aliases:
          - db-${GATEWAY_NAME}
networks:
  default:
    external: true
    name: proxy
