---
name: Linter

on:
  push:
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  shellcheck:
    name: Lint Shell Files
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master

  markdownlint:
    name: Lint Markdown
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'
      - name: Install dependencies
        run: |
          npm install -g markdownlint-cli
      - name: Run markdownlint
        run: |
          markdownlint \
            --config .lint/.markdownlint.json \
            --ignore-path .lint/.markdownlintignore \
            "**/*.md"

  yamllint:
    name: Lint YAML files
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - name: Run yamllint
        run: 'yamllint -c .lint/.yamllint.yml .'

  lint-ignition-views:
    name: Lint Ignition Views
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: '3.13'
      - name: Install ign-lint
        run: pip install ign-lint==0.5.0
      - name: Lint Ignition views
        run: ign-lint --config .ignition-lint.json --files "**/view.json"
